services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
      - "8444:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pigeon
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0074
      KEYCLOAK_AUTH_SERVER_URL: https://keycloak:8443
      KEYCLOAK_REALM: pigeon-race
      KEYCLOAK_CLIENT_ID: admin-cli
      KEYCLOAK_ADMIN_USERNAME: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://keycloak:8443/realms/pigeon-race
      SERVER_SSL_KEY_STORE: /app/keystore.p12
      SERVER_SSL_KEY_STORE_PASSWORD: password
      SERVER_SSL_KEY_STORE_TYPE: PKCS12
    volumes:
      - ./keystore.p12:/app/keystore.p12:ro
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - pigeon-network

  db:
    image: postgres:15
    container_name: postgres-db-pigeon-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0074
      POSTGRES_DB: pigeon
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pigeon-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    ports:
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_KEY_STORE_FILE: /opt/keycloak/conf/server.keystore.p12
      KC_HTTPS_KEY_STORE_PASSWORD: password
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/pigeon
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 0074
    command:
      - start-dev
      - --https-key-store-password=password
      - --https-key-store-file=/opt/keycloak/conf/server.keystore.p12
    volumes:
      - ./keystore.p12:/opt/keycloak/conf/server.keystore.p12:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pigeon-network

networks:
  pigeon-network:
    driver: bridge

volumes:
  postgres_data:
