# Spring app configuration
spring.application.name=PigeonSkyRace
server.port=8082

# Database Configuration
spring.datasource.url=jdbc:postgresql://db:5432/pigeon
spring.datasource.username=postgres
spring.datasource.password=0074
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Keycloak Configuration
keycloak.auth-server-url=https://keycloak:8443
keycloak.realm=pigeon-race
keycloak.resource=pigeon-race-client
keycloak.credentials.secret=fKLOPc1FFyK2vFGHtjZDnQtc8ytpO4YR
keycloak.public-client=false
keycloak.bearer-only=true
keycloak.admin.username=admin
keycloak.admin.password=admin

# OAuth2 Resource Server Configuration
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://keycloak:8443/realms/pigeon-race/protocol/openid-connect/certs

# SSL Configuration
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12

# Logging Configuration
logging.level.com.PigeonSkyRace=DEBUG
logging.level.org.keycloak=DEBUG
logging.level.org.springframework.security=DEBUG


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.doc-expansion=none

# Enable Swagger UI
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true