# Spring app configuration
spring.application.name=PigeonSkyRace
server.port=8082

# Database Configuration
spring.datasource.url=jdbc:postgresql://db:5432/pigeon
spring.datasource.username=postgres
spring.datasource.password=0074
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Keycloak Configuration
keycloak.auth-server-url=https://keycloak:8443
keycloak.realm=pigeon-race
keycloak.client-id=admin-cli
keycloak.admin.username=admin
keycloak.admin.password=admin

# OAuth2 Resource Server Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://keycloak:8443/realms/pigeon-race

# SSL Configuration
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12

# Logging Configuration
logging.level.com.PigeonSkyRace=DEBUG
logging.level.org.keycloak=DEBUG
logging.level.org.springframework.security=DEBUG